services:
  app-backend:
    restart: always
    container_name: khajanchi-api
    build: 
      context: ../../
      dockerfile: ./packages/backend/Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=${DB_HOST:-db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-mydbpwd}
      - DB_DATABASE=${DB_DATABASE:-khajanchi}
      - DB_DIALECT=${DB_DIALECT:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - khajanchi-api-node_modules:/usr/app/packages/backend/node_modules
      - .:/usr/app/packages/backend
    ports:
      - "9000:3000"
    working_dir: /usr/app/packages/backend
    command: >
      sh -c '
        if [ -z "$${OPENAI_API_KEY}" ]; then
          echo "Error: OPENAI_API_KEY is not set"
          exit 1
        fi
        pnpm run db:migrate && pnpm run db:seed:all && pnpm run dev
      '
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: mysql:8.4
    container_name: khajanchi-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-mydbpwd}
      - MYSQL_DATABASE=${DB_DATABASE:-khajanchi}
    ports:
      - "3306:3306"
    volumes:
      - khajanchi-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  khajanchi-api-node_modules:
  khajanchi-db-data:
